### ISSUE TITLE
Transição do botão

### ISSUE THREAD

**Issue by Emanuel-Marques** [francisbowe/htmlcss#1]
### Ajustando o código que faz a transição
Fiz algumas correções para que a transição funcione de maneira suave usando o transition.
Ao invés de usar o `display: none;` para ocultar o texto, eu usei o `overflow`, porque o display não funciona com o transition, abaixo estarão as modificações feitas no seu código CSS.
```css
.botoes{
   background-color: white;
   border-radius: 3px;
   border: none;
   margin: 0 auto;
   position: relative;
   top: 40%;
   left: 15%;
   font-size: 1em;
   width: 25px;
   /*Escondendo o texto caso ultrapasse as larguras do botão*/
   overflow:hidden;
   /*Transição do tamanho do botão*/
   transition: width 0.7s ease-in-out;
   display: inline-flex;
   /*Alinhando o ícone e o texto*/
   align-items: baseline;
}

#btext {
    padding-left: 10px;
}

#btext a {
    text-decoration: none;
    color: green;
}
.botoes:hover {
    width: 200px;
    justify-content: center;
    padding: 5px;
    cursor: pointer;
}
``` 

Aguardando o seu feedback @francisbowe
